# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'PreCommitHooks' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PreCommitHooks
  pod 'SwiftLint'

  target 'PreCommitHooksTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PreCommitHooksUITests' do
    # Pods for testing
  end

end

pre_install do |installer|
  flag =  `sh pre_install.sh`
  Pod::UI.puts flag
end
